평가 최종 지표
1. faithfulness(ragas): 생성된 응답이 제공된 컨텍스트(문서 조각)에 기반한 사실과 일치하는지 평가
2. relevancy(ragas): 응답이 사용자의 질문과 관련되어 있는지 평가
3. context precision(정답지와 참고 문서의 관련성 비교)(ragas): 응답에 사용된 정보가 정확히 컨텍스트에서 추출된 정보인지, 즉 질문에 필요한 정보만 포함되었는지를 평가
    * 0.91
    * context precision@k
4. sentence Transformer(all-minilm-l6-v2): sentence-bert
    * 코사인 유사도 결과: 0.9
    * 정상적인 비교-판단: accuracy 0.74

In [ ]:
import os
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

from itertools import product
from datasets import Dataset
from tqdm import tqdm
tqdm.pandas()

import sys
sys.path.append('../code/graphParser')
from rateLimit import handle_rate_limits

from pydantic import BaseModel, Field
from typing import List

from ragas import evaluate
from ragas.dataset_schema import SingleTurnSample
from ragas.metrics import answer_relevancy, context_precision, faithfulness
from ragas.llms.base import llm_factory
from ragas.embeddings.base import embedding_factory

from langchain_core.prompts import load_prompt
from langchain_core.output_parsers import PydanticOutputParser
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings

from sentence_transformers import SentenceTransformer

In [6]:
dataset = pd.read_csv('../data/rag/rerank_dataset.csv')
# dataset = pd.read_csv('../data/rag/generate_dataset.csv')
dataset['reference_contexts'] = dataset['reference_contexts'].apply(lambda x : eval(x))
dataset['cohere_contexts'] = dataset['cohere_contexts'].apply(lambda x : eval(x))
dataset['rerank_contexts'] = dataset['cohere_contexts'].apply(lambda x : '\n\n'.join(['document_{i}: \n{context}'.format(i=i, context=context) for i, context in enumerate(x[:9])]))
dataset = dataset[['user_input', 'reference_contexts', 'reference', 'synthesizer_name', 'reference_contexts_section', 'cohere_contexts']]

In [2]:
llm = ChatOpenAI(model='gpt-4o-mini', temperature=0.2)
embeddings = OpenAIEmbeddings()

ragas_llm = llm_factory('gpt-4o-mini')
ragas_embedding = embedding_factory()

In [3]:
@handle_rate_limits
def generate_chain(data_batches, llm, current_api_key=None, max_concurrency=5) -> List:
    prompt = load_prompt('../prompt/generate/generate.yaml')
    chain = prompt | llm 
    results = chain.batch(data_batches, config={"max_concurrency": max_concurrency})
    return [result.content for result in results]

In [18]:
max_concurrency = 5
temperatures = [0.0, 0.2, 0.4, 0.6]
rerank_k_list = [5, 6, 7, 8, 9]

for temperature, rerank_k in product(temperatures, rerank_k_list):
    results = []
    input_querys = dataset['user_input'].to_list()
    documents = dataset['cohere_contexts'][:rerank_k]

    llm = ChatOpenAI(model='gpt-4o-mini', temperature=temperature)

    for i in tqdm(range(len(input_querys) // max_concurrency)):
        input_query_batches = input_querys[i * max_concurrency : (i + 1) * max_concurrency]
        documents_batches = documents[i * max_concurrency : (i + 1) * max_concurrency]

        data_batches = [{'input_query': input_query, 'documents': documents} for input_query, documents in zip(input_query_batches, documents_batches)]

        # results.extend(generate_chain(data_batches, llm, max_concurrency=max_concurrency))

    if len(input_querys) % max_concurrency != 0:
        input_query_batches = input_querys[len(input_querys) // max_concurrency * max_concurrency:]
        documents_batches = documents[len(documents) // max_concurrency * max_concurrency:]
        
        data_batches = [{'input_query': input_query, 'documents': documents} for input_query, documents in zip(input_query_batches, documents_batches)]
        
        # results.extend(generate_chain(data_batches, llm, max_concurrency=max_concurrency))

    dataset[f'generate_{temperature}_{rerank_k}'] = results
    # dataset.to_csv('../data/rag/generate_dataset.csv', index=False)

# 1. Sentence Transformer

In [ ]:
dataset = pd.read_csv('../data/rag/generate_dataset.csv')
dataset['reference_contexts'] = dataset['reference_contexts'].apply(lambda x : eval(x))
dataset['cohere_contexts'] = dataset['cohere_contexts'].apply(lambda x : eval(x))

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [ ]:
embedding_df = pd.DataFrame()

reference_embeddings = model.encode(dataset['reference'])

for column in [column for column in dataset.columns if 'generate' in column]:
    tmp_embeddings = model.encode(dataset[column])
    cosine_similarities = cosine_similarity(reference_embeddings, tmp_embeddings)
    embedding_df[column] = cosine_similarities.diagonal()

In [31]:
embedding_df.apply(lambda x : np.mean(x), axis=0)

generate_0.2_5    0.845872
generate_0.2_6    0.870824
generate_0.2_7    0.868940
generate_0.2_8    0.844572
generate_0.2_9    0.869681
generate_0.0_5    0.843107
generate_0.0_6    0.847477
generate_0.0_7    0.844477
generate_0.0_8    0.851046
generate_0.0_9    0.860832
generate_0.4_5    0.850284
generate_0.4_6    0.873566
generate_0.4_7    0.846318
generate_0.4_8    0.845453
generate_0.4_9    0.867021
generate_0.6_5    0.860586
generate_0.6_6    0.859462
generate_0.6_7    0.868231
generate_0.6_8    0.846074
generate_0.6_9    0.856307
dtype: float32

# 2. RAGAS: faithfulness, relevancy, context precision

In [ ]:
for column in [column for column in dataset.columns if 'generate' in column]:
    k = int(column.split('_')[-1])

    result_df = pd.DataFrame()
    
    max_concurrency = 5
    for i in range(len(dataset) // max_concurrency):
        user_input_batches = dataset.iloc[i * max_concurrency : (i + 1) * max_concurrency]['user_input'].to_list()
        answer_batches = dataset.iloc[i * max_concurrency : (i + 1) * max_concurrency][column].to_list()
        contexts_batches = dataset.iloc[i * max_concurrency : (i + 1) * max_concurrency]['cohere_contexts'].apply(lambda x : x[:k]).to_list()
        ground_truth_batches = dataset.iloc[i * max_concurrency : (i + 1) * max_concurrency]['reference'].to_list()[:k]

        data_samples = {
            'question': user_input_batches,
            'answer': answer_batches,
            'contexts': contexts_batches,
            'ground_truth': ground_truth_batches
        }
    
        tmp_dataset = Dataset.from_dict(data_samples)

        # score = evaluate(tmp_dataset, metrics=[answer_relevancy, context_precision, faithfulness])
        score_df = score.to_pandas()
        result_df = pd.concat([result_df, score_df], ignore_index=True)

    if len(dataset) % max_concurrency != 0:
        user_input_batches = dataset.iloc[len(dataset) // max_concurrency * max_concurrency:]['user_input'].to_list()
        answer_batches = dataset.iloc[len(dataset) // max_concurrency * max_concurrency:][column].to_list()
        contexts_batches = dataset.iloc[len(dataset) // max_concurrency * max_concurrency:]['cohere_contexts'].apply(lambda x : x[:k]).to_list()
        ground_truth_batches = dataset.iloc[len(dataset) // max_concurrency * max_concurrency:]['reference'].to_list()[:k]
        
        data_samples = {
            'question': user_input_batches,
            'answer': answer_batches,
            'contexts': contexts_batches,
            'ground_truth': ground_truth_batches
        }
        
        tmp_dataset = Dataset.from_dict(data_samples)
    
        # score = evaluate(tmp_dataset, metrics=[answer_relevancy, context_precision, faithfulness])
        score_df = score.to_pandas()
        result_df = pd.concat([result_df, score_df], ignore_index=True)
    
    # result_df.to_csv(f'../data/rag/generate_score_{column.replace('generate_', '').replace('.', '')}.csv', index=False)

In [ ]:
dataset = pd.read_csv('../data/rag/rerank_dataset.csv')
data_path = '../data/experiment/generate'

result = pd.DataFrame()
for path in os.listdir(data_path):
    k = path.split('_')[-1].replace('.csv', '')
    temperature = path.split('_')[-2]
    temperature = temperature[0] + '.' + temperature[1]

    path = os.path.join(data_path, path)

    data = pd.read_csv(path)
    data['synthesizer_name'] = dataset['synthesizer_name']

    condition = ~pd.isnull(data.loc[:, data.columns[-3:]]).any(axis=1)

    data = data.loc[condition]
    tmp = data.groupby('synthesizer_name').agg({'answer_relevancy': 'mean', 'context_precision': 'mean', 'faithfulness': 'mean'})
    tmp2 = data.agg({'answer_relevancy': 'mean', 'context_precision': 'mean', 'faithfulness': 'mean'}).to_frame().T

    # k와 temperature를 tmp와 tmp2에 각각 추가하지 않고, 최종 결합 시점에만 추가
    tmp = tmp.reset_index()
    tmp = tmp.melt(id_vars=['synthesizer_name'], var_name='metric', value_name='value')
    tmp['synthesizer_metric'] = tmp['synthesizer_name'] + '_' + tmp['metric']
    tmp = tmp.pivot_table(columns='synthesizer_metric', values='value').reset_index(drop=True)
    
    tmp2 = tmp2.melt(var_name='metric', value_name='value')
    tmp2['synthesizer_metric'] = 'overall_' + tmp2['metric']
    tmp2 = tmp2.pivot_table(columns='synthesizer_metric', values='value').reset_index(drop=True)

    # k와 temperature를 최종 결합 시점에 추가
    combined = pd.concat([tmp2, tmp], axis=1)
    combined['k'] = k
    combined['temperature'] = temperature
    result = pd.concat([result, combined], ignore_index=True)

result = result.reset_index(drop=True)
result.columns.name = None
result = result.loc[:, ['k', 'temperature'] + result.columns[:-2].tolist()]

In [91]:
result.sort_values(by='overall_faithfulness', ascending=False).head(10)

,k,temperature,overall_answer_relevancy,overall_context_precision,overall_faithfulness,body part_answer_relevancy,body part_context_precision,body part_faithfulness,"exercise name, body part_answer_relevancy","exercise name, body part_context_precision",...,exercise name_faithfulness,multi_hop_abstract_query_synthesizer_answer_relevancy,multi_hop_abstract_query_synthesizer_context_precision,multi_hop_abstract_query_synthesizer_faithfulness,multi_hop_specific_query_synthesizer_answer_relevancy,multi_hop_specific_query_synthesizer_context_precision,multi_hop_specific_query_synthesizer_faithfulness,single_hop_specifc_query_synthesizer_answer_relevancy,single_hop_specifc_query_synthesizer_context_precision,single_hop_specifc_query_synthesizer_faithfulness
14,9,0.4,0.816992,0.980639,0.892975,0.877720,0.997049,0.925000,0.772987,1.000000,...,0.880540,0.845409,0.956511,0.930697,0.883456,0.997222,0.726429,0.871204,0.916009,1.0000
3,8,0.0,0.813508,0.981351,0.868785,0.876531,0.998214,0.905000,0.771547,0.997768,...,0.821732,0.835971,0.954614,0.905983,0.866851,1.000000,0.688095,0.870973,0.915533,1.0000
19,9,0.6,0.805075,0.976588,0.867294,0.870837,0.997049,0.884167,0.770957,0.996311,...,0.860000,0.786623,0.956511,0.876559,0.892221,0.997222,0.723766,0.881274,0.888013,1.0000
18,8,0.6,0.798212,0.983912,0.866331,0.898092,0.998214,0.922857,0.774337,0.997768,...,0.800833,0.744663,0.981863,0.847527,0.800597,1.000000,0.762338,0.869242,0.908231,1.0000
13,8,0.4,0.817592,0.980318,0.865551,0.905809,0.998214,0.886190,0.773125,1.000000,...,0.881548,0.770867,0.951114,0.873937,0.875621,1.000000,0.724167,0.883982,0.915533,1.0000
12,7,0.4,0.812145,0.987500,0.863419,0.851891,1.000000,0.927778,0.778831,1.000000,...,0.843386,0.779444,0.966893,0.822222,0.899614,1.000000,0.721693,0.871024,0.947123,1.0000
4,9,0.0,0.827154,0.979751,0.860407,0.883954,0.997049,0.900000,0.744307,0.995784,...,0.917370,0.841495,0.956511,0.852374,0.874276,0.997222,0.630635,0.870754,0.916009,1.0000
9,9,0.2,0.816624,0.985541,0.858402,0.880409,0.997049,0.904762,0.777778,0.996311,...,0.884425,0.851399,0.977663,0.855983,0.786539,0.997222,0.679246,0.871024,0.916009,1.0000
2,7,0.0,0.786362,0.981193,0.850653,0.874550,1.000000,0.862143,0.778490,1.000000,...,0.853030,0.786647,0.953401,0.797911,0.783630,1.000000,0.766138,0.873062,0.917401,1.0000
15,5,0.6,0.820570,0.984874,0.847078,0.864643,1.000000,0.784167,0.777707,1.000000,...,0.752857,0.859737,0.969979,0.918681,0.887761,1.000000,0.795952,0.869450,0.938542,0.9375

In [92]:
result.sort_values(by='overall_context_precision', ascending=False).head(10)

,k,temperature,overall_answer_relevancy,overall_context_precision,overall_faithfulness,body part_answer_relevancy,body part_context_precision,body part_faithfulness,"exercise name, body part_answer_relevancy","exercise name, body part_context_precision",...,exercise name_faithfulness,multi_hop_abstract_query_synthesizer_answer_relevancy,multi_hop_abstract_query_synthesizer_context_precision,multi_hop_abstract_query_synthesizer_faithfulness,multi_hop_specific_query_synthesizer_answer_relevancy,multi_hop_specific_query_synthesizer_context_precision,multi_hop_specific_query_synthesizer_faithfulness,single_hop_specifc_query_synthesizer_answer_relevancy,single_hop_specifc_query_synthesizer_context_precision,single_hop_specifc_query_synthesizer_faithfulness
10,5,0.4,0.820622,0.988409,0.840978,0.868960,1.000000,0.873214,0.761953,1.000000,...,0.859167,0.800378,0.972024,0.783135,0.897881,1.000000,0.741667,0.870619,0.938542,1.0000
12,7,0.4,0.812145,0.987500,0.863419,0.851891,1.000000,0.927778,0.778831,1.000000,...,0.843386,0.779444,0.966893,0.822222,0.899614,1.000000,0.721693,0.871024,0.947123,1.0000
6,6,0.2,0.833789,0.986197,0.813355,0.867747,1.000000,0.806922,0.773187,1.000000,...,0.822421,0.853532,0.970060,0.809382,0.882935,1.000000,0.641667,0.870205,0.923333,1.0000
16,6,0.6,0.818878,0.986049,0.839340,0.860854,1.000000,0.738016,0.769793,1.000000,...,0.921717,0.796353,0.970476,0.826696,0.890184,1.000000,0.707500,0.871172,0.923333,1.0000
9,9,0.2,0.816624,0.985541,0.858402,0.880409,0.997049,0.904762,0.777778,0.996311,...,0.884425,0.851399,0.977663,0.855983,0.786539,0.997222,0.679246,0.871024,0.916009,1.0000
15,5,0.6,0.820570,0.984874,0.847078,0.864643,1.000000,0.784167,0.777707,1.000000,...,0.752857,0.859737,0.969979,0.918681,0.887761,1.000000,0.795952,0.869450,0.938542,0.9375
0,5,0.0,0.819549,0.984874,0.795270,0.884684,1.000000,0.764374,0.777729,1.000000,...,0.822641,0.785894,0.958135,0.798639,0.884225,1.000000,0.648016,0.873067,0.938542,1.0000
18,8,0.6,0.798212,0.983912,0.866331,0.898092,0.998214,0.922857,0.774337,0.997768,...,0.800833,0.744663,0.981863,0.847527,0.800597,1.000000,0.762338,0.869242,0.908231,1.0000
1,6,0.0,0.817046,0.983051,0.826394,0.874035,1.000000,0.867143,0.771602,1.000000,...,0.743135,0.790314,0.956488,0.790441,0.878243,1.000000,0.734524,0.871024,0.923333,1.0000
11,6,0.4,0.798129,0.981806,0.786699,0.887918,1.000000,0.770357,0.769926,1.000000,...,0.770723,0.777918,0.953141,0.773077,0.870758,1.000000,0.629167,0.871243,0.923333,1.0000

In [93]:
result.sort_values(by='overall_context_precision', ascending=False).head(10)

,k,temperature,overall_answer_relevancy,overall_context_precision,overall_faithfulness,body part_answer_relevancy,body part_context_precision,body part_faithfulness,"exercise name, body part_answer_relevancy","exercise name, body part_context_precision",...,exercise name_faithfulness,multi_hop_abstract_query_synthesizer_answer_relevancy,multi_hop_abstract_query_synthesizer_context_precision,multi_hop_abstract_query_synthesizer_faithfulness,multi_hop_specific_query_synthesizer_answer_relevancy,multi_hop_specific_query_synthesizer_context_precision,multi_hop_specific_query_synthesizer_faithfulness,single_hop_specifc_query_synthesizer_answer_relevancy,single_hop_specifc_query_synthesizer_context_precision,single_hop_specifc_query_synthesizer_faithfulness
10,5,0.4,0.820622,0.988409,0.840978,0.868960,1.000000,0.873214,0.761953,1.000000,...,0.859167,0.800378,0.972024,0.783135,0.897881,1.000000,0.741667,0.870619,0.938542,1.0000
12,7,0.4,0.812145,0.987500,0.863419,0.851891,1.000000,0.927778,0.778831,1.000000,...,0.843386,0.779444,0.966893,0.822222,0.899614,1.000000,0.721693,0.871024,0.947123,1.0000
6,6,0.2,0.833789,0.986197,0.813355,0.867747,1.000000,0.806922,0.773187,1.000000,...,0.822421,0.853532,0.970060,0.809382,0.882935,1.000000,0.641667,0.870205,0.923333,1.0000
16,6,0.6,0.818878,0.986049,0.839340,0.860854,1.000000,0.738016,0.769793,1.000000,...,0.921717,0.796353,0.970476,0.826696,0.890184,1.000000,0.707500,0.871172,0.923333,1.0000
9,9,0.2,0.816624,0.985541,0.858402,0.880409,0.997049,0.904762,0.777778,0.996311,...,0.884425,0.851399,0.977663,0.855983,0.786539,0.997222,0.679246,0.871024,0.916009,1.0000
15,5,0.6,0.820570,0.984874,0.847078,0.864643,1.000000,0.784167,0.777707,1.000000,...,0.752857,0.859737,0.969979,0.918681,0.887761,1.000000,0.795952,0.869450,0.938542,0.9375
0,5,0.0,0.819549,0.984874,0.795270,0.884684,1.000000,0.764374,0.777729,1.000000,...,0.822641,0.785894,0.958135,0.798639,0.884225,1.000000,0.648016,0.873067,0.938542,1.0000
18,8,0.6,0.798212,0.983912,0.866331,0.898092,0.998214,0.922857,0.774337,0.997768,...,0.800833,0.744663,0.981863,0.847527,0.800597,1.000000,0.762338,0.869242,0.908231,1.0000
1,6,0.0,0.817046,0.983051,0.826394,0.874035,1.000000,0.867143,0.771602,1.000000,...,0.743135,0.790314,0.956488,0.790441,0.878243,1.000000,0.734524,0.871024,0.923333,1.0000
11,6,0.4,0.798129,0.981806,0.786699,0.887918,1.000000,0.770357,0.769926,1.000000,...,0.770723,0.777918,0.953141,0.773077,0.870758,1.000000,0.629167,0.871243,0.923333,1.0000